# Generated by Django 4.2.5 on 2023-09-11 22:53

from django.db import migrations, models
import django.db.models.deletion
import formation.utils.base_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250, verbose_name='descripción')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=10, verbose_name='estado de disponibilidad')),
                ('image', models.ImageField(default='default.png', upload_to=formation.utils.base_model.upload_image, verbose_name='imagen')),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='nombre área')),
            ],
            options={
                'verbose_name': 'área formación',
                'verbose_name_plural': 'áreas de formación',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TypeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_program', models.CharField(choices=[('técnico', 'Técnico'), ('tecnólogo', 'Tecnólogo'), ('operador', 'Operador'), ('especialización', 'Especialización'), ('auxiliar', 'Auxiliar')], max_length=15, unique=True, verbose_name='tipo de programa')),
            ],
            options={
                'verbose_name': 'tipo de programa',
                'verbose_name_plural': 'tipos de programas',
                'ordering': ['type_program'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250, verbose_name='descripción')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=10, verbose_name='estado de disponibilidad')),
                ('image', models.ImageField(default='default.png', upload_to=formation.utils.base_model.upload_image, verbose_name='imagen')),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.CharField(max_length=100, unique=True, verbose_name='nombre del programa')),
                ('area', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='formation.formationarea', verbose_name='área de formación')),
                ('type_program', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='formation.typeprogram', verbose_name='tipo de programa')),
            ],
            options={
                'verbose_name': 'programa',
                'verbose_name_plural': 'programas',
                'ordering': ['program'],
            },
        ),
    ]
