# Generated by Django 4.2.5 on 2023-09-13 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='type_program',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='type_programs', to='formation.typeprogram', verbose_name='tipo de programa'),
        ),
    ]
