# Generated by Django 4.1.7 on 2023-09-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_alter_program_type_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationarea',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='typeprogram',
            name='type_program',
            field=models.CharField(choices=[('técnico', 'Técnico'), ('tecnólogo', 'Tecnólogo'), ('operario', 'Operario'), ('especialización', 'Especialización'), ('auxiliar', 'Auxiliar')], max_length=15, unique=True, verbose_name='tipo de programa'),
        ),
    ]
