# Generated by Django 4.1.7 on 2023-09-21 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common_questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonquestion',
            name='answer',
            field=models.TextField(default=uuid.UUID('ec450fbf-0d8a-4c7e-ae67-0af5ed5aa91a'), max_length=1000),
        ),
        migrations.AlterField(
            model_name='commonquestion',
            name='question',
            field=models.CharField(default=uuid.UUID('8a349703-d43d-40b4-8461-d2c2d2c0e1c6'), max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='commonquestion',
            name='slug',
            field=models.SlugField(default='baa7acf8064f45c9a99c2c58412713b5', max_length=100, unique=True),
        ),
    ]
