# Generated by Django 4.2.5 on 2023-09-20 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='slug',
            field=models.SlugField(default='e51bd2ef7c7b40fab7ea8803c77cc36d', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='testimony',
            field=models.TextField(default=uuid.UUID('33478e7d-2e3b-49a7-9450-a38ed93488f2'), max_length=500),
        ),
    ]
