# Generated by Django 4.1.7 on 2023-09-21 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_alter_testimony_slug_alter_testimony_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='slug',
            field=models.SlugField(default='baa7acf8064f45c9a99c2c58412713b5', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='testimony',
            field=models.TextField(default=uuid.UUID('ef53344a-9952-4df5-9363-3f9abee8187c'), max_length=500),
        ),
    ]
