# Generated by Django 4.2.5 on 2023-09-13 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='título del área')),
                ('description', models.TextField(max_length=100, null=True, verbose_name='descripción')),
                ('partner', models.CharField(max_length=400, null=True, verbose_name='nombre de la persona')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ofinas',
                'verbose_name_plural': 'oficinas',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SubOfficeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='título del área')),
                ('description', models.TextField(max_length=100, null=True, verbose_name='descripción')),
                ('partner', models.CharField(max_length=400, null=True, verbose_name='nombre de la persona')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='offices.officesmodel', verbose_name='oficinas')),
            ],
            options={
                'verbose_name': 'sub oficina',
                'verbose_name_plural': 'sub oficinas',
                'ordering': ['title', 'partner'],
            },
        ),
    ]
