# Generated by Django 4.2.5 on 2023-09-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officesmodel',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subofficemodel',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=150, null=True, unique=True),
        ),
    ]
